
name: Testes automaticos

on: [push]

jobs:
  testar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4
      
      - name: Mostrar arquivos
        run: ls -la

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pytest
        run: pip install pytest

      - name: Executar testes
        run: pytest